IGNORE_COLS = ["push_flag_count","http_cookie_size", "http_cookie_mean", "http_cookie_std", "http_cookie_ssr", 
            "http_get_count", "http_post_count", "http_put_count", "http_delete_count", "http_head_count", "http_patch_count",
            "http_payload_size", "http_payload_mean", "http_payload_std", "http_payload_ssr",
            "http_header_size", "http_header_mean", "http_header_std", "http_header_ssr",
            "http_auth_count", "http_packet_count",  "transmission_rate", "num_connection_per_dst", "tcp_window_size", "tcp_window_size_mean", "tcp_window_size_std", "tcp_window_size_ssr", 
            "xmas_packets_count", "http_options_count", "http_trace_count", "ping_request_count", 
            "http_header_count", "http_rst_stream_count",  
            "ssh_packet_size", "ssh_packet_size_mean", "ssh_packet_size_std", "ssh_packet_size_ssr", 
            "http_auth_count" , "urg_flag_count", "receiver",  "src_ip", "dst_ip", "tcp_state", "ex_seq_num",  
            "init_out_of_order", "close_out_of_order", "ex_ack_number",
            "min_ttl", "max_ttl", "retransmission_packets", "idle_connections", "request_interaval", "response_interval", "last_request_ts", "last_response_ts", 
            "retransmission_rate", "throughput", "packet_loss_count", "packet_loss_rate", "zero_window_count", "zero_window_frequency","request_interval_mean", "response_interval_mean", 
            "max_window_size", "min_window_size",
            "tcp_payload_size", "tcp_payload_mean", "tcp_payload_std", "tcp_payload_ssr", "max_tcp_payload_size", "min_tcp_payload_size",
            "request_interval_mean", 
            "icmp_packet_count", "icmp_error_count",
              "http_success_count",
            "http_client_side_error_count", 
            "http_server_side_error_count",
            "http_rst_stream_count", 
            "http_data_frame_count",
            "http_goaway_count", 
            "http_frame_size", "http_frame_size_mean", "http_frame_size_std", "http_frame_size_ssr",
            "malfolded_user_agent_count", 
            "malfolded_accept_encoding_count", 
            "malfolded_accept_language_count", 
            "bad_http_header_count", 
            "null_flags_count", 
            "ssh_packet_count", 
            "ssh_init_key_exchange_count", 
            "ssh_auth_count",
            "ssh_userauth_failure_count", 
            "ssh_userauth_success_count",
            "tcp_fragmented_packet_count", 
            "ssh_connection_ps",
            "start_sec", 
            "win_start_ts_ssh",
            "http_connection_p5s",
            "win_start_ts", 
            "win_http_pks", 
            "win_con_attempt", 
            "win_ter_attempt", 
            "connection_est_attempts_ps", 
            "connection_ter_attempts_ps"
            ]
        